# Generated by Django 3.1.5 on 2021-01-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_application_casestudy_company_info_component_distributor_events_history_product_reasons_to_choose_re'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseStudy',
            new_name='Case_Study',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('OT', 'Other'), ('3D', '3D Measurement'), ('DH', 'Data Hubs'), ('SO', 'Software'), ('CS', 'CMA Systems')], default='OT', max_length=2),
        ),
    ]
