# Generated by Django 3.1.5 on 2021-01-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210118_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.AlterModelOptions(
            name='case_study',
            options={'verbose_name': 'Case Study', 'verbose_name_plural': 'Case Studies'},
        ),
        migrations.AlterModelOptions(
            name='company_info',
            options={'verbose_name': 'Company Info', 'verbose_name_plural': 'Company Info'},
        ),
        migrations.AlterModelOptions(
            name='reasons_to_choose',
            options={'verbose_name': 'Reasons to Choose', 'verbose_name_plural': 'Reasons to Choose'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('3D', '3D Measurement'), ('CS', 'CMA Systems'), ('DH', 'Data Hubs'), ('SO', 'Software'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
