# Generated by Django 3.1.5 on 2021-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210118_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'History'},
        ),
        migrations.AddField(
            model_name='distributor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SO', 'Software'), ('CS', 'CMA Systems'), ('3D', '3D Measurement'), ('DH', 'Data Hubs'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='reasons_to_choose',
            name='category',
            field=models.CharField(choices=[('R', 'Research'), ('C', 'Clinical')], default='R', max_length=1),
        ),
    ]
