# Generated by Django 3.1.5 on 2021-01-18 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210118_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('OT', 'Other'), ('3D', '3D Measurement'), ('CS', 'CMA Systems'), ('SO', 'Software'), ('DH', 'Data Hubs')], default='OT', max_length=2),
        ),
    ]
