# Generated by Django 3.1.5 on 2021-01-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210118_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4)),
                ('person_name', models.CharField(max_length=200)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='')),
                ('role', models.CharField(max_length=140)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('DH', 'Data Hubs'), ('CS', 'CMA Systems'), ('OT', 'Other'), ('3D', '3D Measurement'), ('SO', 'Software')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='reasons_to_choose',
            name='category',
            field=models.CharField(choices=[('C', 'Clinical'), ('R', 'Research')], default='R', max_length=1),
        ),
    ]
