# Generated by Django 3.1.5 on 2021-01-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210118_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonsToChoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body_text', models.TextField()),
                ('category', models.CharField(choices=[('C', 'Clinical'), ('R', 'Research')], default='R', max_length=1)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reasons to Choose',
                'verbose_name_plural': 'Reasons to Choose',
            },
        ),
        migrations.RenameModel(
            old_name='Case_Study',
            new_name='CaseStudy',
        ),
        migrations.RenameModel(
            old_name='Company_Info',
            new_name='CompanyInfo',
        ),
        migrations.RenameModel(
            old_name='Research_Application',
            new_name='ResearchApplication',
        ),
        migrations.DeleteModel(
            name='Reasons_To_Choose',
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'verbose_name_plural': 'Case Studies'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('3D', '3D Measurement'), ('OT', 'Other'), ('CS', 'CMA Systems'), ('DH', 'Data Hubs'), ('SO', 'Software')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
