# Generated by Django 3.1.5 on 2021-01-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210118_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('OT', 'Other'), ('3D', '3D Measurement'), ('CS', 'CMA Systems'), ('SO', 'Software'), ('DH', 'Data Hubs')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='reasonstochoose',
            name='category',
            field=models.CharField(choices=[('R', 'Research'), ('C', 'Clinical')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('MGMT', 'Management'), ('ADVS', 'Advisors')], default='KEYC', max_length=4),
        ),
    ]
