# Generated by Django 3.1.5 on 2021-01-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210119_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('DH', 'Data Hubs'), ('SO', 'Software'), ('CS', 'CMA Systems'), ('OT', 'Other'), ('3D', '3D Measurement')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='reasonstochoose',
            name='category',
            field=models.CharField(choices=[('C', 'Clinical'), ('R', 'Research')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
