# Generated by Django 3.1.5 on 2021-01-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210119_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body_text', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='application',
            old_name='product',
            new_name='product_link',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='product',
            new_name='product_link',
        ),
        migrations.RemoveField(
            model_name='application',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='application',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='title',
        ),
        migrations.RemoveField(
            model_name='component',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='component',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='component',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reasonstochoose',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='reasonstochoose',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='reasonstochoose',
            name='title',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='title',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SO', 'Software'), ('DH', 'Data Hubs'), ('3D', '3D Measurement'), ('CS', 'CMA Systems'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='reasonstochoose',
            name='category',
            field=models.CharField(choices=[('R', 'Research'), ('C', 'Clinical')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('MGMT', 'Management'), ('ADVS', 'Advisors')], default='KEYC', max_length=4),
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
        migrations.AddField(
            model_name='application',
            name='featureditem',
            field=models.ForeignKey(db_column='featureditem_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='featureditem',
            field=models.ForeignKey(db_column='featureditem_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='component',
            name='featureditem',
            field=models.ForeignKey(db_column='featureditem_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='product',
            name='featureditem',
            field=models.ForeignKey(db_column='featureditem_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='reasonstochoose',
            name='featureditem',
            field=models.ForeignKey(db_column='featureditem_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='featureditem',
            field=models.ForeignKey(db_column='featureditem_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
    ]
