# Generated by Django 3.1.5 on 2021-01-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210119_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='component',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='reasonstochoose',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='researchapplication',
            name='featured',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CS', 'CMA Systems'), ('OT', 'Other'), ('3D', '3D Measurement'), ('DH', 'Data Hubs'), ('SO', 'Software')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('MGMT', 'Management'), ('ADVS', 'Advisors'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.page')),
            ],
        ),
    ]
