# Generated by Django 3.1.5 on 2021-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210119_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('DH', 'Data Hubs'), ('OT', 'Other'), ('CS', 'CMA Systems'), ('3D', '3D Measurement'), ('SO', 'Software')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='reasonstochoose',
            name='category',
            field=models.CharField(choices=[('C', 'Clinical'), ('R', 'Research')], default='R', max_length=1),
        ),
    ]
