# Generated by Django 3.1.5 on 2021-01-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20210119_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Software', 'Software'), ('Data Hubs', 'Data Hubs'), ('3D Measurement', '3D Measurement'), ('CMA Systems', 'CMA Systems'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
