# Generated by Django 3.1.5 on 2021-01-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20210120_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.producttype'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('MGMT', 'Management'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
