# Generated by Django 3.1.5 on 2021-01-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20210120_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(default='study'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reasonstochoose',
            name='category',
            field=models.CharField(choices=[('R', 'Research'), ('C', 'Clinical')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
