# Generated by Django 3.1.5 on 2021-01-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20210120_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
        migrations.CreateModel(
            name='ContentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('body_text', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content Objects',
            },
        ),
    ]
