# Generated by Django 3.1.5 on 2021-01-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20210120_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasonstochoose',
            name='category',
            field=models.CharField(choices=[('research', 'research'), ('clinical', 'clinical')], default='clinical', max_length=10),
        ),
    ]
