# Generated by Django 3.1.5 on 2021-01-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20210120_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='headshot',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
