# Generated by Django 3.1.5 on 2021-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20210123_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='product_link',
        ),
        migrations.AddField(
            model_name='application',
            name='product_link',
            field=models.ManyToManyField(to='website.Product'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('MGMT', 'Management'), ('ADVS', 'Advisors'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
