# Generated by Django 3.1.5 on 2021-01-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20210125_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
