# Generated by Django 3.1.5 on 2021-01-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20210129_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentobject',
            options={'verbose_name': 'Content Form Response', 'verbose_name_plural': 'Content Form Responses'},
        ),
    ]
