# Generated by Django 3.1.5 on 2021-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20210129_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('F', 'Footer'), ('H', 'Header')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('MGMT', 'Management'), ('ADVS', 'Advisors'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
