# Generated by Django 3.1.5 on 2021-01-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20210129_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_page_parent_+', to='website.Page'),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('H', 'Header'), ('F', 'Footer')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
