# Generated by Django 3.1.5 on 2021-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_auto_20210129_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='list_data',
            field=models.CharField(blank=True, choices=[("('', 'ReasonsToChoose', 'CaseStudy', 'Product', 'Component', 'Application', 'ResearchApplication')", "('', 'ReasonsToChoose', 'CaseStudy', 'Product', 'Component', 'Application', 'ResearchApplication')")], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
