# Generated by Django 3.1.5 on 2021-01-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20210129_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='list_data',
            field=models.CharField(blank=True, choices=[('Rea', 'ReasonsToChoose'), ('Cas', 'CaseStudy'), ('Pro', 'Product'), ('Com', 'Component'), ('App', 'Application'), ('Res', 'ResearchApplication')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('F', 'Footer'), ('H', 'Header')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('MGMT', 'Management'), ('KEYC', 'Key Contact'), ('ADVS', 'Advisors')], default='KEYC', max_length=4),
        ),
    ]
