# Generated by Django 3.1.5 on 2021-01-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20210129_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='list_data_heading_links',
            field=models.BooleanField(default=False, help_text='Selecting this will mean that when used in a menu, this page will add jump links for its sub-items.', verbose_name='Add heading links'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
