# Generated by Django 3.1.5 on 2021-01-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_auto_20210130_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='list_data',
            field=models.CharField(blank=True, choices=[('Movem', 'Movement Analysis - Clinical'), ('Movem', 'Movement Analysis - Research'), ('Case ', 'Case Studies'), ('Event', 'Events'), ('Team ', 'Team Members'), ('Histo', 'History'), ('Conta', 'Contact Distributors'), ('Produ', 'Product -3D Measurement'), ('Produ', 'Product -Software'), ('Produ', 'Product -Data Hubs'), ('Produ', 'Product -Other Measurement Components'), ('Produ', 'Product -Complete Movement Analysis Systems')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('F', 'Footer'), ('H', 'Header')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
