# Generated by Django 3.1.5 on 2021-01-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_auto_20210130_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='list_data',
            field=models.CharField(blank=True, choices=[('Movement Analysis - Clinical', 'Movement Analysis - Clinical'), ('Movement Analysis - Research', 'Movement Analysis - Research'), ('Case Studies', 'Case Studies'), ('Events', 'Events'), ('Team Members', 'Team Members'), ('History', 'History'), ('Contact Distributors', 'Contact Distributors'), ('Product - 3D Measurement', 'Product - 3D Measurement'), ('Product - Software', 'Product - Software'), ('Product - Data Hubs', 'Product - Data Hubs'), ('Product - Other Measurement Components', 'Product - Other Measurement Components'), ('Product - Complete Movement Analysis Systems', 'Product - Complete Movement Analysis Systems')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
