# Generated by Django 3.1.5 on 2021-01-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20210131_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='list_data',
            field=models.CharField(blank=True, choices=[('MA-CLI', 'MA-CLI'), ('MA-RES', 'MA-RES'), ('CASE', 'CASE'), ('EVENT', 'EVENT'), ('TEAM', 'TEAM'), ('HIST', 'HIST'), ('DISTR', 'DISTR'), ('Product - 3D Measurement', 'Product - 3D Measurement'), ('Product - Software', 'Product - Software'), ('Product - Data Hubs', 'Product - Data Hubs'), ('Product - Other Measurement Components', 'Product - Other Measurement Components'), ('Product - Complete Movement Analysis Systems', 'Product - Complete Movement Analysis Systems')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('MGMT', 'Management'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
