# Generated by Django 3.1.5 on 2021-01-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_auto_20210131_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.testimonial'),
        ),
        migrations.AlterField(
            model_name='page',
            name='list_data',
            field=models.CharField(blank=True, choices=[('MA-CLI', 'MA-CLI'), ('MA-RES', 'MA-RES'), ('CASE', 'CASE'), ('EVENT', 'EVENT'), ('TEAM', 'TEAM'), ('HIST', 'HIST'), ('DISTR', 'DISTR'), ('PR-3D ', 'PR-3D '), ('PR-Sof', 'PR-Sof'), ('PR-Dat', 'PR-Dat'), ('PR-Oth', 'PR-Oth'), ('PR-Com', 'PR-Com')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='list_data_format',
            field=models.CharField(choices=[('grid', 'grid'), ('accordion', 'accordion'), ('accordion - card', 'accordion - card'), ('people', 'people'), ('columns', 'columns')], default='grid', help_text='How would you like the data to be shown?', max_length=20, verbose_name='List Layout'),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('H', 'Header'), ('F', 'Footer')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('MGMT', 'Management'), ('ADVS', 'Advisors'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
