# Generated by Django 3.1.5 on 2021-02-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_auto_20210131_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Form Response', 'verbose_name_plural': 'Contact Form Responses'},
        ),
        migrations.RemoveField(
            model_name='history',
            name='year',
        ),
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(default='YEAR', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='body_text',
            field=models.TextField(blank=True, help_text='This will appear above all the other content on the page', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='list_data',
            field=models.CharField(blank=True, choices=[('MA-CLI', 'Movement Analysis - Clinical'), ('MA-RES', 'Movement Analysis - Research'), ('CASE', 'Case Studies'), ('EVENT', 'Events'), ('TEAM', 'Team Members'), ('HIST', 'History'), ('DISTR', 'Contact Distributors'), ('PR-3D ', 'Product - 3D Measurement'), ('PR-Sof', 'Product - Software'), ('PR-Dat', 'Product - Data Hubs'), ('PR-Oth', 'Product - Other Measurement Components'), ('PR-Com', 'Product - Complete Movement Analysis Systems')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='testimonial',
            field=models.ForeignKey(blank=True, help_text='This will appear below all the other content on the page', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.testimonial'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
