# Generated by Django 3.1.5 on 2021-02-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_auto_20210201_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='component',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='history',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reasonstochoose',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('F', 'Footer'), ('H', 'Header')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('MGMT', 'Management'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
