# Generated by Django 3.1.5 on 2021-02-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_auto_20210201_0655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='researchapplication',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('H', 'Header'), ('F', 'Footer')], default='H', max_length=1, unique=True),
        ),
    ]
