# Generated by Django 3.1.5 on 2021-02-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_auto_20210201_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='list_data',
            field=models.CharField(blank=True, choices=[('MA-CLI', 'Movement Analysis - Clinical'), ('MA-RES', 'Movement Analysis - Research'), ('CASE', 'Case Studies'), ('EVENT', 'Events'), ('TEAM', 'Team Members'), ('HIST', 'History'), ('DISTR', 'Contact Distributors')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('F', 'Footer'), ('H', 'Header')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
