# Generated by Django 3.1.5 on 2021-02-08 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_auto_20210203_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 22, 47, 57, 406649)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('MGMT', 'Management'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
