# Generated by Django 3.1.5 on 2021-02-08 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_auto_20210208_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 22, 49, 52, 865474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
