# Generated by Django 3.1.5 on 2021-02-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_auto_20210208_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureditem',
            options={'verbose_name': 'Featured Items on the Home Page', 'verbose_name_plural': 'Featured Items on the Home Page'},
        ),
        migrations.AddField(
            model_name='featureditem',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.application'),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.product'),
        ),
        migrations.AlterField(
            model_name='featureditem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.page'),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('F', 'Footer'), ('H', 'Header')], default='H', max_length=1, unique=True),
        ),
    ]
