# Generated by Django 3.1.5 on 2021-02-11 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_auto_20210211_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureditem',
            name='application',
        ),
        migrations.RemoveField(
            model_name='featureditem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='featureditem',
            name='product',
        ),
        migrations.AddField(
            model_name='application',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='component',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='history',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='reasonstochoose',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.featureditem'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('MGMT', 'Management'), ('ADVS', 'Advisors')], default='KEYC', max_length=4),
        ),
    ]
