# Generated by Django 3.1.5 on 2021-02-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_auto_20210211_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='about',
        ),
    ]
