# Generated by Django 3.1.5 on 2021-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_auto_20210215_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='body_text',
            field=models.TextField(blank=True, help_text='You can use Markdown here for rich text.', null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='body_text',
            field=models.TextField(blank=True, help_text='You can use Markdown here for rich text.', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='body_text',
            field=models.TextField(blank=True, help_text='You can use Markdown here for rich text.', null=True),
        ),
        migrations.AlterField(
            model_name='contentobject',
            name='body_text',
            field=models.TextField(help_text='You can use Markdown here.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_text',
            field=models.TextField(blank=True, help_text='You can use Markdown here.', null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='body_text',
            field=models.TextField(blank=True, help_text='You can use Markdown here for rich text.', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='body_text',
            field=models.TextField(blank=True, help_text='This will appear above all the other content on the page. You can use Markdown here.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_text',
            field=models.TextField(blank=True, help_text='You can use Markdown here for rich text.', null=True),
        ),
        migrations.AlterField(
            model_name='reasonstochoose',
            name='body_text',
            field=models.TextField(blank=True, help_text='You can use Markdown here for rich text.', null=True),
        ),
        migrations.AlterField(
            model_name='researchapplication',
            name='body_text',
            field=models.TextField(blank=True, help_text='You can use Markdown here for rich text.', null=True),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('F', 'Footer'), ('H', 'Header')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('MGMT', 'Management'), ('KEYC', 'Key Contact'), ('ADVS', 'Advisors')], default='KEYC', max_length=4),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='body_text',
            field=models.TextField(blank=True, help_text='You can use Markdown here.', null=True),
        ),
    ]
