# Generated by Django 3.1.5 on 2021-02-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_auto_20210215_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reason_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='website.reasonstochoose'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('MGMT', 'Management'), ('ADVS', 'Advisors')], default='KEYC', max_length=4),
        ),
    ]
