# Generated by Django 3.1.5 on 2021-02-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_auto_20210215_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='reason_link',
        ),
        migrations.AddField(
            model_name='application',
            name='reason_to_choose',
            field=models.CharField(choices=[('research', 'research'), ('clinical', 'clinical')], default='research', max_length=15),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('MGMT', 'Management'), ('ADVS', 'Advisors'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
