# Generated by Django 3.1.5 on 2021-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_auto_20210215_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='list_text',
            field=models.CharField(blank=True, help_text='If you want something other than the lead text to appear in the Case Study list, put that here.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reason_to_choose',
            field=models.CharField(choices=[('research', 'research'), ('clinical', 'clinical')], default='research', help_text='Does this Application belong to "Clinical Services" or "Research Facilities"?', max_length=15),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('H', 'Header'), ('F', 'Footer')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
