# Generated by Django 3.1.5 on 2021-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0083_auto_20210215_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='grid_list',
            field=models.BooleanField(default=False, help_text='Use a grid list at the top of the product list page'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('KEYC', 'Key Contact'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
