# Generated by Django 3.1.5 on 2021-02-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_auto_20210215_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
    ]
