# Generated by Django 3.1.5 on 2021-02-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0086_auto_20210215_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='case_study_link',
            field=models.ManyToManyField(blank=True, to='website.CaseStudy'),
        ),
        migrations.AlterField(
            model_name='application',
            name='product_link',
            field=models.ManyToManyField(blank=True, to='website.Product'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('ADVS', 'Advisors'), ('MGMT', 'Management'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
