# Generated by Django 3.1.5 on 2021-02-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0088_auto_20210215_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='lead_text',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('MGMT', 'Management'), ('ADVS', 'Advisors'), ('KEYC', 'Key Contact')], default='KEYC', max_length=4),
        ),
    ]
