# Generated by Django 3.1.5 on 2021-02-16 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_auto_20210216_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='testimonial',
            field=models.ForeignKey(blank=True, help_text='This will appear below all the other content on the page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.testimonial'),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('H', 'Header'), ('F', 'Footer')], default='H', max_length=1, unique=True),
        ),
    ]
