# Generated by Django 3.1.5 on 2021-02-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_auto_20210216_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
