# Generated by Django 3.1.5 on 2021-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0093_auto_20210217_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['order', 'title'], 'verbose_name_plural': 'Case Studies'},
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ['order', 'area', 'name']},
        ),
        migrations.AddField(
            model_name='distributor',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('MGMT', 'Management'), ('ADVS', 'Advisors')], default='KEYC', max_length=4),
        ),
    ]
