# Generated by Django 3.1.5 on 2021-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0094_auto_20210217_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasonstochoose',
            options={'ordering': ['category', 'order', 'title'], 'verbose_name': 'Reasons to Choose', 'verbose_name_plural': 'Reasons to Choose'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['person_type', 'person_name', 'role']},
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('F', 'Footer'), ('H', 'Header')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('KEYC', 'Key Contact'), ('ADVS', 'Advisors'), ('MGMT', 'Management')], default='KEYC', max_length=4),
        ),
    ]
