# Generated by Django 3.1.5 on 2021-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0095_auto_20210217_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='application'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='casestudy'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='component'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event'),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='history'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('H', 'Header'), ('F', 'Footer')], default='H', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='person_type',
            field=models.CharField(choices=[('MGMT', 'Management'), ('KEYC', 'Key Contact'), ('ADVS', 'Advisors')], default='KEYC', max_length=4),
        ),
    ]
