# Generated by Django 3.1.5 on 2021-02-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0098_auto_20210219_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemenu',
            name='title',
            field=models.CharField(choices=[('F', 'Footer'), ('H', 'Header')], default='H', max_length=1, unique=True),
        ),
    ]
